name: panelCapture

channels:
  - conda-forge
  - bioconda
  - defaults
#  - compbiocore  # For Perl packages needed by Achab

dependencies:
  - cromwell=58
  - bwa=0.7.15
  - fastp=0.20.0
  - gatk4=4.2.0.0
  - qualimap
  - sambamba=0.6.6
  - samtools=1.9
# WARN: 'prod' env actually use v1.4(.0) of bcftools
#       -> But through conda, I get a 'libcrypto' error with this version
#       -> Instead use same version as samtools
  - bcftools=1.9
  - bedtools=2.26.0
  - crumble=0.8.2
  - vcftools=0.1.16
  - perl=5.26.2
# Even if it seem to install fine with lower versions, multiQC v1.14 actually require Python >= 3.8:
# (some modules break otherwise)
# WARN: Bellow will conflict with bioperl which requires Python < 3.8
  - python=3.8
  - multiqc=1.14
# Achab:
#  - mobidic-mpa=1.2.6
#  - perl-bioperl=1.7.2
#  - perl-excel-writer-xlsx=1.00
#  - perl-switch=2.17
# Really need to pin bellow ?
#  - r-base=3.5.1 # (automatically got v3.6.2)

#prefix: /mnt/Bioinfo/Softs/src/conda/envs/panelCapture
